---
# tasks file for osp-vm

  - name: Get current OSP-related Bash env vars
    shell: "env | grep OS_"
    register: osp_vars
    changed_when: false

  - name: Print current OSP-related Bash env vars (for debugging, if required)
    debug:
      var: osp_vars.stdout_lines
    changed_when: false

  - name: Ensuring authentication can occur with current OSP-related Bash env vars
    os_auth:
      auth_type: password
    changed_when: false


  - name: create VM.
    os_server:
      region_name: "{{ osp_vm.region_name }}"
      auth:  "{{ osp_vm.api }}"
      name: "{{ item.1.vm.name }}"
      image: "{{ item.1.vm.image }}"
      flavor: "{{ item.1.vm.flavor }}"
      network: "{{ item.1.vm.network }}"
      auto_ip: "{{ item.1.vm.auto_ip }}"
      key_name: "{{ item.1.vm.key_name }}"
      state: "{{ item.1.vm.server_state }}"
      with_dict:
        - "{{ osp_vm.vm }}"



