---
# tasks file for osp-vm

  - name: talk to the api and get auth
    os_auth:
      cert: "{{ user_cert }}"
      key: "{{ user_key }}"
      cacert: "{{ user_cacert }}"
      region_name: "{{ region }}"

  - name: get facts about about the VM's
    os_server_facts:
      cert: "{{ user_cert }}"
      key: "{{ user_key }}"
      cacert: "{{ user_cacert }}"
      region_name: "{{ region }}"
      server: "{{ server_name }}"
    debug:
      var: openstack_servers
    register: found_vm

  - name: create VM if is not there
    os_server:
      cert: "{{ user_cert }}" 
      key: "{{ user_key }}"
      cacert: "{{ user_cacert }}"
      region_name: "{{ region }}"
      auth:
        auth_url: "{{ auth_url }}" # example > https://my-osp.com:5001/v2.0
        username: "{{ username }}"
        password: "{{ user_passwd }}"
        project_name: "{{ osp_project }}"
      name: "{{ server_name }}"
      image: "{{ server_image }}"
      flavor: "{{ server_flavor }}"
      network: "{{ server_network }}"
      auto_ip: "{{ server_ip }}"
      key_name: "{{ user_key }}"
      state: "{{ server_state }}"


    when:


