---
# tasks file for osp-vm

  - name: talk to the api and get auth
    os_auth:
      cert:
      key:
      cacert:
      region_name:

  - name: get facts about about the VM's
    os_server_facts:
      cert:
      key:
      cacert:
      region_name:
      server: web*
    debug:
      var: openstack_servers
    register: found_vm

  - name: create VM if is not there
    os_server_action:
      cert:
      key:
      cacert:
      region_name:
      action: create
      auth:
        auth_url: https://my-osp.com:5001/v2.0
        username:
        password:
      project_name:
      server: web45


